id = "vixen"
name = "Vixen"
version = "0.1.0"
schema_version = 1
description = "Vixen language support."
repository = "https://github.com/bearcove/vixen"
authors = ["Amos Wenger <amos@bearcove.eu>"]
themes = []
icon_themes = []
languages = ["languages/vixen"]
capabilities = []

[lib]

[grammars.vixen]
repository = "https://github.com/bearcove/tree-sitter-vixen"
rev = "fde0a8d8a057c217ae9ee8c1fb4ceaa00d10f0d9"
path = "."

[language_servers.vx-lsp]
name = "Vixen LSP"
languages = ["Vixen"]

[context_servers]

[agent_servers]

[slash_commands]
